language: python

python:
  - "2.6"
  - "2.7"

services:
  - mysql
  - postgresql
  - memcached

notifications:
  email:
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#services-dev"
    use_notice: false
    skip_join: false

install:
  - make build
  - ./local/bin/pip install psycopg2

before_script:
  - mysql -e 'create database sync_test;'
  - psql -c 'create database sync_test;' -U postgres

script:
  - make test
  - MOZSVC_SQLURI=pymysql://root@localhost/sync_test make test
  - MOZSVC_SQLURI=postgresql://postgres@localhost/sync_test make test
